import { Document, model, Model, Schema } from "mongoose";

export interface IHotel extends Document{
	type:string;
	hotel:{
		type:string;
		hotelId:string;
		chainCode:string;
		dupeId:string;
		rating:string;
		cityCode:string;
		latitude:number;
		longitude:number;
		hotelDistance:{}
		address:{
			cityName:string;
			countryCode:string;
		}
		contact:{
			phone:string;
		}
		description:{
			lan:string;
			text:string;
		}
		amenities:Array<string>
		media:Array<{
			uri:string;
			category:string;
		}>
	}
	available:boolean;
	offers:Array<{
		id:string;
		checkInDate:string;
		checkOutDate:string;
		rateCode:string;
		guests:{
			adults:number;
		}
		price:{
			currency:string;
			base:string;
			total:string;
		}
	}>;
	self:string;
}
const HotelSchema = new Schema({
	type:{type:String},
	hotel:{
		hotelId:String,
		chainCode:String,
		dupeId:String,
		rating:String,
		cityCode:String,
		latitude:Number,
		longitude:Number,
		hotelDistance:{},
		address:{
			cityName:String,
			countryCode:String,
		},
		contact:{
			phone:String,
		},
		description:{
			lan:String,
			text:String,
		},
		amenities:[{type:String}],
		media:[{
			uri:String,
			category:String,
		}],
	},
	available:Boolean,
	offers:[{
		id:String,
		checkInDate:String,
		checkOutDate:String,
		rateCode:String,
		guests:{
			adults:Number
		},
		price:{
			currency:String,
			base:String,
			total:String
		}
	}],
	self:String
})
export const Hotels:Model<IHotel> = model('hotels',HotelSchema)
