import { Document, model, Model, Schema } from "mongoose";

export interface IHotel extends Document{
	type:string;
	location:{
		type:string,
		coordinates:Array<number>
	}
	hotel:{
		type:string;
		hotelId:string;
		chainCode:string;
		dupeId:string;
		rating:number;
		cityCode:string;
		latitude:number;
		longitude:number;
		hotelDistance:{}
		address:{
			cityName:string;
			countryCode:string;
		}
		contact:{
			phone:string;
		}
		description:{
			lan:string;
			text:string;
		}
		amenities:Array<string>
		media:Array<{
			uri:string;
			category:string;
		}>
	}
	available:boolean;
	offers:Array<{
		id:string;
		checkInDate:string;
		checkOutDate:string;
		rateCode:string;
		guests:{
			adults:number;
		}
		price:{
			currency:string;
			base:number;
			total:number;
		}
	}>;
	self:string;
}
const HotelSchema = new Schema({
	type:{type:String},
	location:{
		type:{
			type:String,
			enum:['Point'],
			required:true
		},
		coordinates:{
			type:[Number],
			required:true
		}
	},
	hotel:{
		hotelId:String,
		chainCode:String,
		dupeId:String,
		rating:Number,
		cityCode:String,
		latitude:Number,
		longitude:Number,
		hotelDistance:{},
		address:{
			cityName:String,
			countryCode:String,
		},
		contact:{
			phone:String,
		},
		description:{
			lan:String,
			text:String,
		},
		amenities:[{type:String}],
		media:[{
			uri:String,
			category:String,
		}],
	},
	available:Boolean,
	offers:[{
		id:String,
		checkInDate:String,
		checkOutDate:String,
		rateCode:String,
		guests:{
			adults:Number
		},
		price:{
			currency:String,
			base:Number,
			total:Number
		}
	}],
	self:String
})
export const Hotels:Model<IHotel> = model('hotels',HotelSchema)
